name: Create release
on:
  push:
    tags:
      - release-*

env:
  BUILD_CONFIGURATION: Release
  TARGET: netstandard2.0
  SOLUTION_FILE_PATH: ProcessSensor.sln

jobs:
  build:
    name: Build release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build
        working-directory: '${{env.GITHUB_WORKSPACE}}'
        run: >-
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}}
          ${{env.SOLUTION_FILE_PATH}}

      - name: Zip build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: >-
          Compress-Archive -Path
          @("bin/${{env.BUILD_CONFIGURATION}}/${{env.TARGET}}/FanControl.ProcessSensor.dll",
          "bin/${{env.BUILD_CONFIGURATION}}/${{env.TARGET}}/FanControl.ProcessSensor.cfg")
          -DestinationPath release.zip

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: true
