name: Create release candidate
on:
  pull_request:
    branches:
      - master

env:
  BUILD_CONFIGURATION: Release
  TARGET: net48
  SOLUTION_FILE_PATH: ProcessSensor.sln

jobs:
  build-rc:
    name: Build release candidate
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build
        working-directory: '${{env.GITHUB_WORKSPACE}}'
        run: >-
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}}
          ${{env.SOLUTION_FILE_PATH}}

      - name: Zip build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: >-
          Compress-Archive -Path
          @("bin/${{env.BUILD_CONFIGURATION}}/${{env.TARGET}}/FanControl.ProcessSensor.dll",
          "bin/${{env.BUILD_CONFIGURATION}}/${{env.TARGET}}/FanControl.ProcessSensor.cfg")
          -DestinationPath release-candidate.zip

      - name: Create draft release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: release-candidate.zip
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}
          tag: "release-candidate_${{ github.head_ref }}"
          artifactErrorsFailBuild: true
