name: Create release candidate
'on':
  pull_request:
    branches:
      - master

env:
  BUILD_CONFIGURATION: Release
  TARGET: netstandard2.0
  SOLUTION_FILE_PATH: .

jobs:
  build-rc:
    name: Build release candidate
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Build
        working-directory: '${{env.GITHUB_WORKSPACE}}'
        run: >-
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}}
          ${{env.SOLUTION_FILE_PATH}}

      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: 'bin/${{env.BUILD_CONFIGURATION}}/${{env.TARGET}}/*'
